[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "GPL-3.0",
    "LGPL-2.1",
    "MIT",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]

[[licenses.clarify]]
name = "encoding_rs"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 },
]
