[package]
name = "flatpak-frontend"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4"
gtk = { version = "0.9", features = ["v3_22"] }
gtk-macros = "0.2.0"
gdk = "0.13.0"
gdk-pixbuf = "0.9.0"
libhandy = { git="https://gitlab.gnome.org/World/Rust/libhandy-rs" }
glib = { version = "0.10", features = ["v2_50"] }
gio = { version = "0.9", features = ["v2_46"] }
gettext-rs= { version = "0.4", features = ["gettext-system"] }
flatpak = { git="https://gitlab.gnome.org/haecker-felix/flatpak-rs" }
appstream-rs = { git = "https://github.com/bilelmoussaoui/appstream-rs/" }
chrono = "0.4.13"
url = "2.1.1"
async-std = "1.4.0"
isahc = {version = "0.9", features = ["json"]}
thiserror = "1.0.20"
futures-util = "0.3.1"
bus = "2.2.3"
