[package]
name = "gnome-store"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4"
gtk-macros = "0.2.0"
gettext-rs= { version = "0.4", features = ["gettext-system"] }
appstream = { git = "https://github.com/bilelmoussaoui/appstream/", features = ["gzip"] }
url = "2.1.1"
async-std = "1.4.0"
isahc = {version = "0.9", features = ["json"]}
thiserror = "1.0.20"
futures-util = "0.3.1"
broadcaster = "1.0.0"
lazy_static = "1.4.0"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
serde_json = "1.0"
chrono = "0.4.15"
html2pango = "0.3.3"
async-process = "0.1.3"
regex = "1.3.9"
dyn-clone = "1.0.2"

[dependencies.gtk]
git = "https://github.com/bilelmoussaoui/gtk4"
branch = "bilelmoussaoui/update"
package = "gtk4"

[dependencies.gdk]
git = "https://github.com/bilelmoussaoui/gdk4"
branch = "bilelmoussaoui/update"
package = "gdk4"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"

[dependencies.gio]
git = "https://github.com/gtk-rs/gio"
features = ["v2_60"]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
features = ["v2_60"]

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"
features = ["v1_44"]

[dependencies.libhandy]
git = "https://gitlab.gnome.org/bilelmoussaoui/libhandy4-rs"
package = "libhandy4"

[dependencies.flatpak]
git = "https://gitlab.gnome.org/haecker-felix/flatpak-rs"
branch = "wip/haecker-felix/update"
